name: Static Project Deployment Pipeline
description: Deploys a static project to RPRs S3 bucket.
inputs:
  AWS_ACCESS_KEY_ID:
    description: The AWS access key ID.
    required: true
    # default: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:
    description: The AWS secret access key.
    required: true
    # default: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION:
    description: The target AWS region.
    required: false
    # default: us-east-1
    default: us-west-1
  AWS_S3_BUCKET:
    description: The target S3 bucket to sync with.
    required: false
    default: rpr.to
  AWS_S3_ENDPOINT:
    description: The AWS endpoint.
    required: false
    default: s3.amazonaws.com
  SOURCE_DIR:
    description: The local directory (or file) you wish to sync/upload to S3.
    required: false
    default: dist
  DEST_DIR:
    description: The directory inside of the S3 bucket you wish to sync/upload to.
    required: false
  CLOUDFRONT_DISTRIBUTION_ID:
    description: The ID of the CloudFront Distribution to be invalidated.
    required: false
    default: E4ZE7H9ALLHAD

runs:
  using: composite
  steps:
    - shell: bash
      run: echo Building project

    - name: Build Package
      uses: SeligLabs/gitactions/build-npm@main
      with:
        NODE_VERSION: 12

    - name: Get Package Name
      id: name
      uses: rockpaperreality/action-deployment/project-name@main
      with:
        override: ${{ inputs.DEST_DIR }}

    - shell: bash
      run: "echo Publishing project to: /${{ steps.name.outputs.name }}"

    - name: Deploy to S3
      uses: SeligLabs/gitactions/s3-deploy@main
      with:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ inputs.AWS_REGION }}
        AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
        SOURCE_DIR: ${{ inputs.SOURCE_DIR }}
        DEST_DIR: ${{ steps.name.outputs.name }}

    - shell: bash
      run: "echo Completed publishing of the project. Now invalidating the path: /${{ steps.name.outputs.name }}/*"

    - name: Invalidate the CloudFront Distribution
      uses: SeligLabs/gitactions/invalidate-cloudfront@main
      with:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ inputs.AWS_REGION }}
        DISTRIBUTION: ${{ inputs.CLOUDFRONT_DISTRIBUTION_ID }}
        PATHS: /${{ steps.name.outputs.name }}/*

    - shell: bash
      run: echo DEPLOYMENT COMPLETE
