name: Get Formatted Name
description: Gets the project name to be used for the project name based upon branch.
author: Selig Labs, Inc <info@seliglabs.com>

inputs:
  override:
    description: An override for the value of the project name.
    required: false

outputs:
  name:
    description: The project name to be used for the project.
    value: ${{ steps.prefix.outputs.prefix }}${{ inputs.override || fromJSON(steps.package.outputs.jsonData).homepage}}

runs:
  using: composite
  steps:
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    - name: Some other step # Output usage example
      with:
        tagname: ${{ steps.tagName.outputs.tag }}
      run: "echo tagName: ${{ steps.tagName.outputs.tag }}"

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Get the Prefix
      id: prefix
      uses: rockpaperreality/action-deployment/get-prefix@test-2
      with:
        branch: ${{ steps.tagName.outputs.tag || steps.branch.outputs.branch-name }}

    - name: Get Package Information
      id: package
      uses: SeligLabs/gitactions/read-json-file@main
