name: Get Formatted Name
description: Gets the project name to be used for the project name based upon branch.
author: Selig Labs, Inc <info@seliglabs.com>

inputs:
  override:
    description: An override for the value of the project name.
    required: false

outputs:
  name:
    description: The project name to be used for the project.
    value: ${{ steps.prefix.outputs.prefix }}${{ inputs.override || fromJSON(steps.package.outputs.jsonData).name}}

runs:
  using: composite
  steps:
    - name: Extract Branch Name
      id: branch
      uses: SeligLabs/gitactions/branch-name@main

    - name: Get the Prefix
      id: prefix
      uses: rockpaperreality/action-deployment/get-prefix@main
      with:
        branch: ${{ steps.branch.outputs.branch }}

    - name: Get Package Information
      id: package
      uses: SeligLabs/gitactions/read-json-file@main
