name: Project Name
description: Gets the correct project name to be used based upon branch and project configurations.
author: Selig Labs, Inc <info@seliglabs.com>

inputs:
  branch:
    description: The branch the triggered the Git Action.
    required: true

outputs:
  prefix:
    description: The desired prefix name
    value: ${{ steps.previx-dev.outputs.PREFIX || steps.previx-qa.outputs.PREFIX || steps.previx-internal.outputs.PREFIX || steps.previx-staging.outputs.PREFIX}}

runs:
  using: composite

  steps:
    - name: Get Prefix dev
      if: contains(inputs.branch , 'dev')
      shell: bash
      run: echo '::set-output name=PREFIX::development-'
      id: previx-dev
    - name: Get Prefix qa
      if: contains(inputs.branch, 'qa')
      shell: bash
      run: echo '::set-output name=PREFIX::qa-'
      id: previx-qa
    - name: Get Prefix internal
      if: contains(inputs.branch, 'internal')
      shell: bash
      run: echo '::set-output name=PREFIX::internal-'
      id: previx-internal
    - name: Get Prefix staging
      if: contains(inputs.branch, 'stag')
      shell: bash
      run: echo '::set-output name=PREFIX::staging-'
      id: previx-staging

  # steps:
  #   - name: Get Prefix
  #     id: prefix
  #     shell: bash
  #     run: |
  #       echo "##[set-output name=value;]$(
  #         case ${{ inputs.branch }} in
  #           dev | development)
  #             echo development-
  #             ;;

  #           qa)
  #             echo qa-
  #             ;;

  #           internal)
  #             echo internal-
  #             ;;

  #           stage | staging)
  #             echo staging-
  #             ;;

  #           *)
  #             echo ""
  #             ;;
  #         esac
  #       )"
