name: Get Name
description: Gets the project name to be used for the project.
author: Selig Labs, Inc <info@seliglabs.com>

inputs:
  override:
    description: An override for the value of the project name.
    required: false

outputs:
  name:
    description: The project name to be used for the project.
    value: ${{ steps.override.outputs.override || steps.name.outputs.name }}

runs:
  using: composite
  steps:
#     - name: Get Override Name
#       id: override
#       uses: rockpaperreality/action-deployment/get-override-name@main

    - name: Get Project Name
      id: name
      uses: rockpaperreality/action-deployment/get-formatted-name@main
      with:
        override: ${{ inputs.override }}
